//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRFELOBOOST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public int AdminsID { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string usertype { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string TelefonNo { get; set; }
    
        public virtual Genders Genders { get; set; }
    }
}
