//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRFELOBOOST.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRF_ELOBOOSTEntities : DbContext
    {
        public FRF_ELOBOOSTEntities()
            : base("name=FRF_ELOBOOSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Adverts> Adverts { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Elooboster> Elooboster { get; set; }
        public virtual DbSet<Games> Games { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<Ranks> Ranks { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Meetings> Meetings { get; set; }
    }
}
